build:
  image: ubuntu:20.4
  before_script:
    - apt-get update
    - apt-get install -y build-essential 
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - poetry install 
    - ./install.sh
  script:
    - echo "Test"
  tags:
    - docker