stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_HOME: "$CI_PROJECT_DIR/.poetry"
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive

sca:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y build-essential python3-dev curl ninja-build cmake g++
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    - export PATH=${POETRY_HOME}/bin:${PATH}
    - poetry config experimental.new-installer false
    - poetry install

  script:
    - set -e
    - poetry run pre-commit install
    - poetry run pre-commit run -a
  tags:
    - docker

build:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y build-essential python3-dev curl ninja-build cmake g++
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    - export PATH=${POETRY_HOME}/bin:${PATH}
    - poetry config experimental.new-installer false
    - poetry install

  script:
    - set -e
    - ./install.sh
  tags:
    - docker
