[tool.poetry]
name = "hannah-tvm"
version = "0.1.0"
description = ""
authors = ["Christoph Gerum <christoph.gerum@uni-tuebingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
torchaudio = "^0.8.1"
torchvision = "^0.9.1"
hydra-core = "^1.0.6"
automate = {path = "external/automate", extras = ["postgres"]}
onnx = "^1.8.1"
xgboost = "^1.3.3"


[tool.poetry.scripts]
hannah-tvm-compile = 'hannah_tvm.compile:main'

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
