[tool.poetry]
name = "hannah-tvm"
version = "0.1.0"
description = ""
authors = ["Christoph Gerum <christoph.gerum@uni-tuebingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
torchaudio = "^0.8.1"
torchvision = "^0.9.1"
hydra-core = "^1.1.0"
onnx = "^1.8.1"
xgboost = "^1.3.3"
artifactory = "^0.1.17"
importlib-metadata = "^4.0.1"
Twisted = "^21.2.0"
prettytable = "^2.1.0"
SQLAlchemy = "^1.4.12"
configparser = "^5.0.2"
pyvcd = "^0.2.4"
pyelftools = "^0.27"
openpyxl = "^3.0.7"
XlsxWriter = "^1.4.0"
PyYAML = "^5.4.1"
numpy = "^1.20.2"
tflite = "^2.4.0"
pyserial = "^3.5"
usb = "^0.0.83-alpha.0"
west = "^0.11.0"
automate = {path = "external/automate", extras = ["postgres"], develop=true}
tvm = {path = "external/tvm/python", develop=true}



[tool.poetry.scripts]
hannah-tvm-compile = 'hannah_tvm.compile:main'
hannah-tvm-tune = 'hannah_tvm.tune:main'
hannah-tvm-bench = 'hannah_tvm.bench:main'
hannah-tvm-memory = 'hannah_tvm.analysis:memory_main'

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
black = "^21.4b0"
pre-commit = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
