defaults:
  - base_config
  - board:
      - jetsonnano_cpu
      - jetsontx2_cpu
      - jetsonagx_cpu
      - n1sdp
  - model:
      - conv-net-trax
      - densenet-121
      - efficientnet-lite4
      - mobilenet-v2
      - resnet-18
      - resnet-50
      - shufflenet
      - squeezenet-1.1
      - vgg16
      - vgg19
      - tinyml_ad01
      - tinyml_ic01
      - tinyml_kws01
      - tinyml_vww01


tuner: null
