defaults:
  - base_config
  - board:
      - jetsonnano_cpu
      - jetsontx2_cpu
      - jetsonagx_cpu
  - model:
      #- densenet-121
      - conv-net-trax
      - efficientnet-lite4
      - mobilenet-v2
      - resnet-18
      - resnet-50
      - shufflenet
      #- squeezenet-1.0
      - squeezenet-1.1
      - vgg16
      - vgg19
  - qconfig: null
